In [62]:
import pandas as pd
df=pd.read_csv('/Users/Guchi/Documents/projects/endtoendmlproject/artifact/raw.csv')

In [63]:
df.head()

age         workclass  education.num      marital.status       occupation  \
0   23           Private             10       Never-married     Adm-clerical   
1   43           Private             10  Married-civ-spouse  Exec-managerial   
2   49  Self-emp-not-inc              4  Married-civ-spouse            Sales   
3   33           Private              9  Married-civ-spouse     Craft-repair   
4   22           Private             10       Never-married     Adm-clerical   

    relationship   race     sex  capital.gain  capital.loss  hours.per.week  \
0  Not-in-family  White  Female             0             0              40   
1        Husband  White    Male             0             0              50   
2        Husband  White    Male             0             0              40   
3        Husband  Black    Male             0             0              40   
4      Own-child  White    Male             0             0              25   

  native.country income  
0  United-States  <=50K  
1  United-States   >50K  
2  United-States  <=50K  
3  United-States  <=50K  
4  United-States  <=50K

In [64]:
raw_data=df
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import  OneHotEncoder,OrdinalEncoder,StandardScaler,LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer

In [95]:
train,test=train_test_split(df,test_size=0.2)
lb=LabelEncoder()

In [96]:
tar_train=lb.fit_transform(train.income)
tar_test=lb.fit_transform(test.income)
train=train.drop('income',axis=1)
test=test.drop('income',axis=1)
raw_data=train

In [97]:

            numerical_column=list(raw_data.select_dtypes(exclude='object').columns)
            one_hot_column=['sex','race']
            categorical_column=list(set(list(raw_data.columns))-set(list(numerical_column + one_hot_column)))
            #logging.info(f'transformation_started{numerical_column}{one_hot_column}{categorical_column}')


            num_pipeline=Pipeline(steps=[
                ('imputer',SimpleImputer(strategy='mean')),
                ('standarad_scaler',StandardScaler(),)
            ])
            cat_pipeline=Pipeline(steps=[
                ('imputer',SimpleImputer(strategy='most_frequent')),
                ('label_encoding',OrdinalEncoder())
            ])
            on_hot_pipeeline=Pipeline(steps=[
                ('imputer',SimpleImputer(strategy='most_frequent')),
                ('one_hot_encode',OneHotEncoder(drop='first'))
            ])
            #logging.info(f'encodingdata')

            preprocessor=ColumnTransformer(
                transformers=[('numpipeline',num_pipeline,numerical_column),
                ('cat_pipeline',cat_pipeline,categorical_column),
                ('one_hot_pipeline',on_hot_pipeeline,one_hot_column)
                ],remainder='drop')


In [98]:
train_arr=preprocessor.fit_transform(train)
test_arr=preprocessor.transform(test)

In [108]:
import numpy as np 
df_qw=np.c_[train_arr,tar_train]
df_qw[:,-1]

array([1., 1., 0., ..., 0., 0., 0.])

In [99]:
preprocessor.get_feature_names_out()

array(['numpipeline__age', 'numpipeline__education.num',
       'numpipeline__capital.gain', 'numpipeline__capital.loss',
       'numpipeline__hours.per.week', 'cat_pipeline__relationship',
       'cat_pipeline__marital.status', 'cat_pipeline__native.country',
       'cat_pipeline__workclass', 'cat_pipeline__occupation',
       'one_hot_pipeline__sex_Male',
       'one_hot_pipeline__race_Asian-Pac-Islander',
       'one_hot_pipeline__race_Black', 'one_hot_pipeline__race_Other',
       'one_hot_pipeline__race_White'], dtype=object)

In [102]:
from sklearn.ensemble import GradientBoostingClassifier
gb=GradientBoostingClassifier()
gb.fit(train_arr,tar_train)
from sklearn.metrics import  classification_report
cls= classification_report(tar_test,gb.predict(test_arr))
print(cls)

              precision    recall  f1-score   support

           0       0.88      0.95      0.92      2482
           1       0.79      0.60      0.68       775

    accuracy                           0.87      3257
   macro avg       0.84      0.78      0.80      3257
weighted avg       0.86      0.87      0.86      3257



In [103]:
new_df=pd.DataFrame(train_arr,columns=preprocessor.get_feature_names_out())

In [104]:
new_df.columns

Index(['numpipeline__age', 'numpipeline__education.num',
       'numpipeline__capital.gain', 'numpipeline__capital.loss',
       'numpipeline__hours.per.week', 'cat_pipeline__relationship',
       'cat_pipeline__marital.status', 'cat_pipeline__native.country',
       'cat_pipeline__workclass', 'cat_pipeline__occupation',
       'one_hot_pipeline__sex_Male',
       'one_hot_pipeline__race_Asian-Pac-Islander',
       'one_hot_pipeline__race_Black', 'one_hot_pipeline__race_Other',
       'one_hot_pipeline__race_White'],
      dtype='object')

In [75]:
from sklearn.preprocessing import  LabelEncoder
lb=LabelEncoder()

x=lb.fit_transform(train.income)
type(x)

numpy.ndarray

In [76]:
train.income

11517    <=50K
4888      >50K
1788     <=50K
5949     <=50K
11624    <=50K
         ...  
14640    <=50K
1116      >50K
12856     >50K
9694     <=50K
6590     <=50K
Name: income, Length: 13024, dtype: object

In [77]:
x

array([0, 1, 0, ..., 1, 0, 0])

In [85]:
y=lb.fit_transform(test.income)

In [86]:
test.income

12428    <=50K
10455    <=50K
13616    <=50K
283      <=50K
12132    <=50K
         ...  
11343    <=50K
975       >50K
6771      >50K
10006    <=50K
14424     >50K
Name: income, Length: 3257, dtype: object

In [87]:
y

array([0, 0, 0, ..., 1, 0, 1])